<?php

namespace ACPT_Lite\Constants;

class HTMLTag
{
	/**
	 * @see https://www.w3schools.com/tags/
	 */
	const ALLOWED_FORMATS = [
		'a' => [
			'target' => [],
			'class' => [],
			'id' => [],
			'href' => [],
			'title' => [],
			'style' => [],
			'data-block-list-id' => [],
			'data-min-blocks' => [],
			'data-max-blocks' => [],
			'data-parent-id' => [],
			'data-layout' => [],
			'data-index' => [],
			'data-group-id' => [],
			'data-target-id' => [],
			'data-media-type' => [],
			'data-parent-index' => [],
			'data-parent-name' => [],
			'data-element' => [],
			'data-elements' => [],
			'data-block-id' => [],
		],
		'abbr' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'acronym' => [],
		'address' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'applet' => [],
		'area' => [],
		'article' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'aside' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'audio' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'b' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'base' => [],
		'basefont' => [],
		'pecifies' => [],
		'bdi' => [],
		'bdo' => [],
		'big' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'blockquote' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'body' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'br' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'button' => [
			'disabled' => [],
			'value' => [],
			'data-id' => [],
			'data-layout' => [],
			'data-multiple' => [],
			'data-accepts' => [],
			'data-max-size' => [],
			'data-min-size' => [],
			'data-media-type' => [],
			'data-parent-index' => [],
			'data-target-id' => [],
			'data-min-blocks' => [],
			'data-max-blocks' => [],
			'readonly' => [],
			'style' => [],
			'multiple' => [],
			'type' => [],
			'name' => [],
			'class' => [],
			'id' => [],
		],
		'canvas' => [],
		'caption' => [],
		'center' => [],
		'circle' => [
			'cx' => [],
			'cy' => [],
			'r' => [],
			'fill' => [],
		],
		'cite' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'code' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'col' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'colgroup' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'data' => [],
		'datalist' => [
			'class' => [],
			'id' => [],
		],
		'dd' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'del' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'details' => [],
		'dfn' => [],
		'dialog' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'dir' => [],
		'efines' => [],
		'div' => [
			'data-prefix' => [],
			'data-value' => [],
			'data-max' => [],
			'data-target' => [],
			'data-target-copy' => [],
			'data-parent-id' => [],
			'data-target-id' => [],
			'data-index' => [],
			'data-id' => [],
			'style' => [],
			'class' => [],
			'id' => [],
			'draggable' => [],
		],
		'dl' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'dt' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'ellipse' => [
			'cx' => [],
			'cy' => [],
			'rx' => [],
			'ry' => [],
			'fill' => [],
		],
		'em' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'embed' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'fieldset' => [
			'class' => [],
			'id' => [],
		],
		'figcaption' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'figure' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'font' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'footer' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'form' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'frame' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'frameset' => [],
		'g' => [
			'fill' => [],
		],
		'h1' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'h2' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'h3' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'h4' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'h5' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'h6' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'head' => [],
		'header' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'hgroup' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'hr' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'html' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'i' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'iframe' => [
			'title' => [],
			'width' => [],
			'height' => [],
			'src' => [],
			'frameborder' => [],
			'allow' => [],
			'allowfullscreen' => [],
		],
		'img' => [
			'class' => [],
			'id' => [],
			'src' => [],
			'alt' => [],
			'title' => [],
		],
		'input' => [
			'list' => [],
			'onchange' => [],
			'data-target-id' => [],
			'data-conditional-rules-id' => [],
			'data-conditional-rules-field-index' => [],
			'data-acpt-validate' => [],
			'data-acpt-validate-blank' => [],
			'data-acpt-validate-blank-message' => [],
			'data-acpt-validate-not-blank' => [],
			'data-acpt-validate-not-blank-message' => [],
			'data-acpt-validate-equals' => [],
			'data-acpt-validate-equals-message' => [],
			'data-acpt-validate-not-equals' => [],
			'data-acpt-validate-not-equals-message' => [],
			'data-acpt-validate-gt' => [],
			'data-acpt-validate-gt-message' => [],
			'data-acpt-validate-gte' => [],
			'data-acpt-validate-gte-message' => [],
			'data-acpt-validate-lt' => [],
			'data-acpt-validate-lt-message' => [],
			'data-acpt-validate-lte' => [],
			'data-acpt-validate-lte-message' => [],
			'data-acpt-validate-minlength' => [],
			'data-acpt-validate-minlength-message' => [],
			'data-acpt-validate-min' => [],
			'data-acpt-validate-min-message' => [],
			'data-acpt-validate-maxlength' => [],
			'data-acpt-validate-maxlength-message' => [],
			'data-acpt-validate-max' => [],
			'data-acpt-validate-max-message' => [],
			'data-acpt-validate-required' => [],
			'data-acpt-validate-required-message' => [],
			'data-acpt-validate-regex' => [],
			'data-acpt-validate-regex-message' => [],
			'data-min-date' => [],
			'data-max-date' => [],
			'data-index' => [],
			'checked' => [],
			'required' => [],
			'aria-required' => [],
			'value' => [],
			'readonly' => [],
			'style' => [],
			'type' => [],
			'name' => [],
			'class' => [],
			'id' => [],
			'minlength' => [],
			'maxlength' => [],
			'min' => [],
			'max' => [],
			'step' => [],
			'pattern' => [],
			'placeholder' => [],
		],
		'ins' => [],
		'kbd' => [],
		'label' => [
			'for' => [],
			'title' => [],
			'style' => [],
			'type' => [],
			'name' => [],
			'class' => [],
			'id' => []
		],
		'legend' => [],
		'li' => [
			'aria-grobbed' => [],
			'role' => [],
			'style' => [],
			'class' => [],
			'id' => [],
			'draggable' => [],
			'data-layout' => [],
			'data-value' => [],
			'data-min-blocks' => [],
			'data-max-blocks' => [],
			'data-field-id' => [],
			'data-block-list-id' => [],
			'data-block-index' => [],
			'data-parent-name' => [],
			'data-media-type' => [],
		],
		'link' => [],
		'main' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'map' => [],
		'mark' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'menu' => [],
		'meta' => [],
		'meter' => [],
		'nav' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'noframes' => [],
		'noscript' => [],
		'object' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'ol' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'optgroup' => [
			'label' => [],
		],
		'option' => [
			'selected' => [],
			'value' => [],
			'label' => [],
			'data-symbol' => [],
			'data-placeholder' => [],
		],
		'output' => [],
		'p' => [
			'class' => [],
			'id' => [],
			'data-message-id' => [],
		],
		'param' => [],
		'path' => [
			'd' => [],
			'fill' => [],
			'opacity' => [],
			'fill-rule' => [],
			'clip-rule' => [],
		],
		'picture' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'pre' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'progress' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'q' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'rp' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'rt' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'ruby' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		's' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'samp' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'script' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'search' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'section' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'select' => [
			'data-conditional-rules-id' => [],
			'data-conditional-rules-field-index' => [],
			'required' => [],
			'readonly' => [],
			'style' => [],
			'multiple' => [],
			'type' => [],
			'name' => [],
			'class' => [],
			'id' => []
		],
		'small' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'source' => [
			'src' => [],
			'type' => [],
		],
		'span' => [
			'style' => [],
			'class' => [],
			'id' => []
		],
		'strike' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'strong' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'style' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'sub' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'summary' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'sup' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'svg' => [
			'xmlns' => [],
			'aria-hidden' => [],
			'role' => [],
			'class' => [],
			'width' => [],
			'height' => [],
			'preserveAspectRatio' => [],
			'viewbox' => [],
			'data-width' => [],
			'data-height' => [],
			'data-icon' => [],
			'style' => [],
			'clip-rule' => [],
		],
		'table' => [
			'data-min-blocks' => [],
			'data-max-blocks' => [],
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'tbody' => [
			'data-min-blocks' => [],
			'data-max-blocks' => [],
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'td' => [
			'colspan' => [],
			'width' => [],
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'template' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'textarea' => [
			'data-conditional-rules-id' => [],
			'data-conditional-rules-field-index' => [],
			'required' => [],
			'rows' => [],
			'cols' => [],
			'readonly' => [],
			'style' => [],
			'multiple' => [],
			'type' => [],
			'name' => [],
			'class' => [],
			'id' => []
		],
		'tfoot' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'th' => [
			'width' => [],
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'thead' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'time' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'title' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'tr' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'track' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'tt' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'u' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
		'ul' => [
			'style' => [],
			'class' => [],
			'id' => [],
			'data-conditional-rules-id' => [],
			'data-min-blocks' => [],
			'data-max-blocks' => [],
		],
		'var' => [],
		'video' => [
			'controls' => [],
			'width' => [],
			'height' => [],
			'muted' => [],
		],
		'wbr' => [
			'style' => [],
			'class' => [],
			'id' => [],
		],
	];
}